Chatbot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chatbot, name='chatbot'),
   
]

SmartCity/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from Vigilantix import views as vigilantix_views

urlpatterns = [
    path('', vigilantix_views.landingpage, name='landingpage'),
    path('saferoute/', include('Vigilantix.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('chatbot/', include('Chatbot.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vigilantix/urls.py
from django.urls import path,re_path
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'Vigilantix'  # Define the namespace here

urlpatterns = [
    path("", views.landingpage, name="landingpage"),
    path("search", views.search, name="search"),
    path("routing", views.routing, name="routing"),
    path("police", views.police, name="police"),
    path("cammera", views.cammera, name="cammera"),
    path("contact", views.contact, name="contact"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("getLocation",views.get_location, name= "getLocation")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Vigilantix/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class CustomUser(AbstractBaseUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    aadhaar = models.IntegerField(null=True)

    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email


class Location(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.latitude}, {self.longitude}"



class PolicStation(models.Model):
    name = models.CharField(max_length=30, default="na")
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.latitude}, {self.longitude}"
    

class SecurityCamera(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.latitude}, {self.longitude}"

Vigilantix/views.py
from django.db import IntegrityError
from django.urls import reverse
import folium
from folium.plugins import MousePosition
import json
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from math import radians, cos, sin, asin, sqrt
from django.http import HttpResponseRedirect, JsonResponse
import openrouteservice
import operator
from functools import reduce
from django.contrib.auth import authenticate, login, logout
from .models import PolicStation,SecurityCamera,CustomUser
import http.client


# def index(request):
#     return render(request,"Vigilantix/landingpage.html")

def landingpage(request):
    return render(request,"Vigilantix\landingpage.html")

def search(request):
    latitude = 27.030703
    longitude = 75.893527
    cradius = 5.0
    # Define the map center
    if request.method == 'POST':
        latitude = float(request.POST.get('latitude'))
        longitude = float(request.POST.get('longitude'))
        cradius = float(request.POST.get('radius'))
    center = [latitude, longitude]

    #creating map
    m = folium.Map(location=center, zoom_start=13)
    folium.LatLngPopup().add_to(m)

    #adding user to map
    tooltip = "Your Location"
    icon=folium.Icon(color='red', prefix='fa', icon='user')
    folium.Marker(location=center, tooltip=tooltip, icon=icon).add_to(m)
    folium.Circle(
        location=center,
        radius=cradius*1000,
        fill=True,
        fill_opacity=0.1,
        color='green'
    ).add_to(m)

    stations = PolicStation.objects.all()
    cameras = SecurityCamera.objects.all()
    radius = cradius  # radius in kilometers
    for station in stations:
        station_latitude = station.latitude
        station_longitude = station.longitude
        dist = haversine(latitude, longitude,station_latitude, station_longitude)
        if dist <= radius:
            marker_location = (station_latitude, station_longitude)
            tooltip = station.name
            icon=folium.Icon(color='blue', prefix='fa',icon='shield')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)
    for camera in cameras:
        camera_latitude = camera.latitude
        camera_longitude = camera.longitude
        dist = haversine(latitude, longitude,camera_latitude, camera_longitude)
        if dist <= radius:
            marker_location = (camera_latitude, camera_longitude)
            tooltip = "Camera"+str(camera.id)
            icon=folium.Icon(color='green', prefix='fa',icon='video-camera')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)
    
    m=m._repr_html_() #updated
    context = {'my_map': m,
                'latitudef':latitude,
                'longitudef':longitude,
                'radiusf':cradius,
               }
    return render(request, 'Vigilantix/map.html', context)

def routing(request):
    latitudefrom = 19.09949
    longitudefrom = 72.86476
    latitudeto = 19.07755
    longitudeto = 72.86591

    # Define the start and end coordinates
    start = (latitudefrom, longitudefrom) 
    end = (latitudeto, longitudeto) 

    # Create the map
    m = folium.Map(location=start, zoom_start=13 , height="100%" )
    folium.LatLngPopup().add_to(m)
    # folium.TileLayer('stamentoner').add_to(m)
    # Add the start and end markers
    folium.Marker(location=start, tooltip='Start').add_to(m)
    folium.Marker(location=end, tooltip='End').add_to(m)

    if request.method == 'POST':
        latitudefrom = float(request.POST.get('latitudefrom'))
        longitudefrom = float(request.POST.get('longitudefrom'))
        latitudeto = float(request.POST.get('latitudeto'))
        longitudeto = float(request.POST.get('longitudeto'))

    m = folium.Map(location=list(reversed([longitudefrom, latitudefrom])), zoom_start=13)
    coords = [[longitudefrom, latitudefrom], [longitudeto, latitudeto]]
    ors_client = openrouteservice.Client(key='5b3ce3597851110001cf6248844ba845bb7648a3bda6b57313f08c0d')

    route = ors_client.directions(coordinates=coords,
                        profile='foot-walking',
                        format='geojson')
    waypoints = list(dict.fromkeys(reduce(operator.concat, list(map(lambda step: step['way_points'], route['features'][0]['properties']['segments'][0]['steps'])))))
    folium.PolyLine(locations=[list(reversed(coord)) for coord in route['features'][0]['geometry']['coordinates']], color="green").add_to(m)
    cradius = 30
    
    stations = PolicStation.objects.all()
    cameras = SecurityCamera.objects.all()
    radius = cradius  # radius in kilometers
    for station in stations:
        station_latitude = station.latitude
        station_longitude = station.longitude
        dist = haversine(latitudefrom, longitudefrom,station_latitude, station_longitude)
        if dist <= radius:
            marker_location = (station_latitude, station_longitude)
            tooltip = station.name
            icon=folium.Icon(color='blue', prefix='fa',icon='shield')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)
        dist = haversine(latitudeto, longitudeto,station_latitude, station_longitude)
        if dist <= radius:
            marker_location = (station_latitude, station_longitude)
            tooltip = station.name
            icon=folium.Icon(color='blue', prefix='fa',icon='shield')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)
    for camera in cameras:
        camera_latitude = camera.latitude
        camera_longitude = camera.longitude
        dist = haversine(latitudefrom, longitudefrom,camera_latitude, camera_longitude)
        if dist <= radius:
            marker_location = (camera_latitude, camera_longitude)
            tooltip = "Camera"+str(camera.id)
            icon=folium.Icon(color='green', prefix='fa',icon='video-camera')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)
        dist = haversine(latitudeto, longitudeto,camera_latitude, camera_longitude)
        if dist <= radius:
            marker_location = (camera_latitude, camera_longitude)
            tooltip = "Camera"+str(camera.id)
            icon=folium.Icon(color='green', prefix='fa',icon='video-camera')
            folium.Marker(location=marker_location, tooltip=tooltip, icon=icon).add_to(m)

    m=m._repr_html_() #updated
    context = {'my_map': m,
                'latitudefrom' : latitudefrom,
                'longitudefrom' : longitudefrom,
                'latitudeto' : latitudeto,
                'longitudeto' : longitudeto,
               }
    return render(request,"Vigilantix/routing.html",context)

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r

def get_location(request):
    if request.method == 'POST':
        # Extract the position data from the request body
        data = json.loads(request.body.decode('utf-8'))
        latitude = data.get('latitude')
        longitude = data.get('longitude')
        print(latitude, longitude, data)

        # Do something with the position data
        # ...
        
        
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})\
            
def police(request):
    if request.method == 'POST':
        name = request.POST.get('psname')
        latitude = request.POST.get('pslat')
        longitude = request.POST.get('pslon')
        selection = request.POST.get('selection')
        print("user selected "+selection)
        if selection == '1':
            polobj = PolicStation(name=name,latitude=latitude,longitude=longitude)
            polobj.save()
        elif selection == '0':
            polobj = SecurityCamera(latitude=latitude,longitude=longitude)
            polobj.save()
    return render(request, 'Vigilantix/police.html',{
        'policelist':PolicStation.objects.all().reverse()
    })


def cammera(request):
    if request.method == 'POST':
        latitude = request.POST.get('cmlat')
        longitude = request.POST.get('cmlon')
        polobj = SecurityCamera(latitude=latitude,longitude=longitude)
        polobj.save()
    return render(request, 'Vigilantix/cammera.html',{
        'camlist':SecurityCamera.objects.all()
    })


def contact(request):
     return render(request, 'Vigilantix/contact.html')


def register(request):
    if request.method == "GET":
        return render(request, "Vigilantix/users.html")
    if request.method == "POST":
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        aadhar = request.POST["aadhar"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        try:
            # Aadhar authentication
            conn = http.client.HTTPSConnection("api.apyhub.com")

            payload = "{\n    \"aadhaar\":\""+aadhar+"\"\n}"

            headers = {
                'apy-token': "APY0W3pTpUGPtk9Bi5DpOENp0Fri0quMrLFoyA4Id7OcO3kRQplqHCl4KNz4mNzZo1E8FUz",
                'Content-Type': "application/json"
                }
            conn.request("POST", "/validate/aadhaar", payload, headers)
            res = conn.getresponse()
            data = res.read()
            print(data.decode("utf-8"))

            json_data = json.loads(data.decode("utf-8"))
            result = json_data["data"]

            print(result)
            # Attempt to create new user

Vigilantix/templates/Vigilantix/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CitySentry</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% tailwind_css %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
</head>

<body class="bg-gray-100 font-serif leading-normal tracking-normal">
    <!-- Navbar -->
    <nav class="bg-[#eee] py-4 text-white top-0 w-full z-10">
        <div class="container mx-auto flex justify-between items-center">
            <!-- Logo or App Name -->
            <div>

                <span class="text-xl font-semibold font-Inter tracking-wider text-black"><a href="">CitySentry</a></span>
            </div>
            <div class="text-lg font-medium text-black font-Inter tracking-wider pl-20 gap-5  justify-center items-center hidden md:flex" style="float: left">
                <div><p>Features </p></div>
                <div><p>About</p></div>
                <div><p>Contact</p></div>
             
            </div>
            <div class="mt-6 flex items-center justify-center gap-4">
                <a href='/chatbot/' class="transform rounded-md bg-black hover:scale-105 ease-in-out duration-500  lg:px-9 px-4 py-1 lg:py-4 font-medium text-white transition-colors ">Chatbot </a>
              </div>
            </div>
        </div>
    </nav>
    {% block body %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
        document.getElementById('menuToggle').addEventListener('click', function() {
        var mobileMenu = document.getElementById('mobileMenu');
        mobileMenu.style.display = mobileMenu.style.display === 'none' || mobileMenu.style.display === '' ? 'block' : 'none';
    });

    function menuShow() {
        var mobileMenu = document.getElementById('mobileMenu');
        mobileMenu.style.display = 'block';
        mobileMenu.style.backgroundColor = 'white';
        mobileMenu.style.position = 'absolute';
        // mobileMenu.style.top = '120%';
        // mobileMenu.style.left = '50%';

    }
    </script>
</body>
</html>

Vigilantix/templates/Vigilantix/index.html
{% extends "Vigilantix/layout.html" %} {% load static %}{% block body %}

<div>Hey this is ME Sudhakar Jha</div>

<h1 class="text-xs border-b color text-sky-400">
  Django + Tailwind CSS + Flowbite
</h1>

{% endblock %} {% block script %}
<!-- Add JS -->
{% endblock %}

Vigilantix/templates/Vigilantix/layout.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en"class="overflow-y-hidden" >
    <head>
        <title>{% block title %}Vigilantix{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'Vigilantix/style.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
        <script src="jquery-3.6.1.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <style> @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap'); </style>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Poppins:wght@300&display=swap" rel="stylesheet">
        {% tailwind_css %}
    </head>
    <body>

    <nav style="background-color: lightgray; color: black; height: 70px" class="flex text-white w-screen">
      <div class="px-5 xl:px-12 py-6 flex w-full items-center">
        <a class="text-3xl font-bold font-heading hover:no-underline " style="color:black; text-decoration:none; font-family: 'Montserrat', sans-serif;" href="#">
          Saferoute
        </a>
      </div>
      <div class="  py-6 flex  items-center align-middle" style="color: black; width:70%;">
        <ul  class=" md:flex items-center align-middle float-left mx-auto font-semibold font-heading space-x-12">
          <li style="width:6rem"><a class=" w-11 hover:text-gray-200 dec " href="{% url 'Vigilantix:search' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">Search</a></li>
          <li style="width:6rem"><a class="hover:text-gray-200" href="{% url 'Vigilantix:routing' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">Routing</a></li>
          <li style="width:8rem"><a class="hover:text-gray-200" href="{% url 'Vigilantix:police' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">Add Your Data</a></li>
          <li style="width:6rem"><a class="hover:text-gray-200" href="{% url 'Vigilantix:contact' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">Contact Us</a></li>
          
          {% if user.is_authenticated %}
          <li>
            <a class="hover:text-gray-200" href="{% url 'Vigilantix:logout' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">
              LOGOUT
              
            </a>
          </li>
          {% else %}
          <li>
            <a class="hover:text-gray-200" href="{% url 'Vigilantix:login' %}" style="text-decoration:none; font-family: 'Poppins', sans-serif; padding:10px 0px 0px 0px">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16" style="margin-right:2rem">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
              </svg>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

        
          
        
        <div class="body"  style="background-color: rgb(25, 24, 24);">
    {% block body %}
    {% endblock %}
        
    </body>
</html>
<script src="{% static 'location.js' %}">

</script>

Vigilantix/templates/Vigilantix/login1.html
{% extends "Vigilantix/layout.html" %} {% block body %}
<div
  class="h-screen flex flex-col items-center"
  style="background-image: linear-gradient(to right, #141b34, #203374)"
>
  <div
    style="
      width: 60%;

      background-image: linear-gradient(
        to left,
        rgba(31, 183, 155, 0.22),
        rgba(113, 65, 191, 0.22)
      );
      border-radius: 20px;
    "
    class="mt-5"
  >
    <h2
      class="mb-4 pt-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
    >
      Login
    </h2>

    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

    <form
      class="form-group flex flex-col items-center"
      action="{% url 'Vigilantix:login' %}"
      method="post"
    >
      {% csrf_token %}
      <div style="width: 60%" class="form-group flex flex-col items-center">
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Longitude"
        >
          Username
        </label>
        <input
          autofocus
          class="shadow text-center appearance-none border-none text-white rounded w-full py-2 px-3 leading-tight focus:outline-none"
          type="text"
          style="background-color: #176693; width: 60%"
          name="username"
          placeholder="Username"
        />
      </div>
      <div style="width: 60%" class="form-group flex flex-col items-center">
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Longitude"
        >
          password
        </label>
        <input
          class="shadow text-center appearance-none border-none text-white rounded w-full py-2 px-3 leading-tight focus:outline-none"
          style="background-color: #176693; width: 60%"
          type="password"
          name="password"
          placeholder="Password"
        />
      </div>
      <input
        tyle="
      width: 11rem;
      box-shadow: 0 0 4px 2px rgba(255, 255, 255, 0.3);
      border: none;
      outline: none;
    "
        class="inline-block border-0 bg-slate-100 px-6 pb-2 mt-8 pt-2.5 text-lg uppercase text-slate-700 font-bold hover:bg-slate-600 hover:shadow-lg hover:border-white transition duration-500 hover:text-white"
        type="submit"
        value="Login"
      />
    </form>
    <div
      class="mb-4 pt-4 text-4xl tracking-tight font-light text-center text-gray-900 dark:text-white"
    >
      Don't have an account? <a href="{% url 'Vigilantix:register' %}">Register here.</a>
    </div>
  </div>
</div>

{% endblock %}

Vigilantix/templates/Vigilantix/routing.html
{% extends "Vigilantix/layout.html" %} {% load static %}{% block body %}

<div class="grid grid-flow-col h-screen gap-0" style="background-color: white;">
  <div
    
    class="col-span-1 w-30 max-h-full"
  >
    <form action="{% url 'Vigilantix:routing' %}" method="post" class="px-8 pt-6 pb-2 mb-4">
      {% csrf_token %}
      <div class="mb-4">
        <div class="block text-lg font-bold mb-2 text-slate-100">FROM</div>
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Latitude"
        >
          Latitude From
        </label>
        <input
          class="shadow text-center appearance-none border-none  rounded w-full py-2 px-3 leading-tight focus:outline-none"
          id="Latitude"
          style="background-color: lightgray"
          type="text"
          name="latitudefrom"
          placeholder="Latitude"
          value="{{latitudefrom}}"
        />
      </div>
      <div class="mb-4">
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Longitude"
        >
          Longitude
        </label>
        <input
          class="shadow text-center appearance-none border-none  rounded w-full py-2 px-3 leading-tight focus:outline-none"
          id="Longitude"
          style="background-color: lightgray"
          type="text"
          name="longitudefrom"
          placeholder="Longitude"
          value="{{longitudefrom}}"
        />
      </div>

      <div class="mb-4">
        <div class="block text-lg font-bold mb-2 text-slate-100">TO</div>
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Latitude"
        >
          Latitude
        </label>
        <input
          class="shadow text-center appearance-none border-none  rounded w-full py-2 px-3 leading-tight focus:outline-none"
          id="Latitude"
          style="background-color: lightgray"
          type="text"
          name="latitudeto"
          placeholder="Latitude"
          value="{{latitudeto}}"
        />
      </div>
      <div class="mb-4">
        <label
          class="block text-center text-lg font-bold mb-2 text-slate-300"
          for="Longitude"
        >
          Longitude
        </label>
        <input
          class="shadow text-center appearance-none border-none rounded w-full py-2 px-3 leading-tight focus:outline-none"
          id="Longitude"

          style="background-color: lightgray"
          type="text"
          name="longitudeto"
          placeholder="Longitude"
          value="{{longitudeto}}"
        />
      </div>

      <div class="flex flex-col items-center">
        <button
   
          class="inline-block border-0 bg-slate-100 px-6 pb-2 mt-8 pt-2.5 text-lg uppercase text-slate-700 font-bold hover:bg-slate-600 hover:shadow-lg hover:border-white transition duration-500 hover:text-white"
        >
          <input type="submit" value="ROUTE" />
        </button>
      </div>
    </form>
  </div>
  <div class="bg-slate-600 col-span-4 h-full">{{ my_map|safe }}</div>
</div>

{% endblock %} {% block script %}
<!-- Add JS -->
<div style="height: 500px; width: 500px">
<script src="{% static 'location.js' %}"></script>
</div>
{% endblock %}

<!--
  This component uses @tailwindcss/forms

  yarn add @tailwindcss/forms
  npm install @tailwindcss/forms

  plugins: [require('@tailwindcss/forms')]
-->
<!--
  This component uses @tailwindcss/forms

  yarn add @tailwindcss/forms
  npm install @tailwindcss/forms

  plugins: [require('@tailwindcss/forms')]
-->